### ISSUE TITLE
Unable to install filesync on eclipse 

### ISSUE THREAD

**Issue by harish-myaccount** [iloveeclipse/filesync4eclipse#47]
Eclipse Version: Mars Release (4.5.0)
Build id: 20150621-1200

An error occurred while installing the items
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]org.eclipse.team.svn 3.0.1.I20150722-1700, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.InstallBundleAction).
The artifact file for osgi.bundle,org.eclipse.team.svn,3.0.1.I20150722-1700 was not found.

**Comment by iloveeclipse** [comment]
Filesync has nothing to do with svn plugin.
